version: "3.4"

services:
    mssql-server:
        container_name: "mssql"
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "KAlex_forum_api2022!"
            MSSQL_PID: Express
        ports:
            - "1433:1433"
        volumes:
            - data:/var/opt/mssql
    
    api:
        container_name: "forumapi"
        image: api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        depends_on:
            - mssql-server  
volumes: 
    data:
  